
global:
  smtp_from: 'prometheus@site1.int'

route:
  group_by: ['instance', 'alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m
  receiver: send_email
# The labels by which incoming alerts are grouped together. For example,
# multiple alerts coming in for cluster=A and alertname=LatencyHigh would
# be batched into a single group.
  routes:
    - receiver: send_email
      match:
        alertname: InstanceDown

receivers:
  - name: send_email
    email_configs:
      - to: 'user1@site1.int'
        smarthost: 192.168.1.42:25
        require_tls: false
