groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 1 minute.'
      summary: Instance {{ $labels.instance }} down
  
  - alert: LinkSpeed200KBps
    expr: rate(node_network_receive_bytes_total{device="ens33"}[10s]) > 204800
    for: 1m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has speed 200KBps.'
      summary: Instance {{ $labels.instance }} has a 200KBps