global:
  scrape_interval:     15s
  evaluation_interval: 15s

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - localhost:9093

rule_files:
  # - "first.rules"
  # - "second.rules"
  # - "alert.rules.yaml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9100
        - 192.168.1.78:9100
        - 192.168.1.80:9100
        - 192.168.1.81:9100

  # - job_name: 'snmp'
  #   static_configs:
  #     - targets:
  #       - 192.168.1.199  # SNMP device.
    # metrics_path: /snmp
    # params:
    #   module: [if_mib]
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__

    #     replacement: 192.168.1.41:9116 #Prometheus server IP