- name: prometheus
  hosts: ub-bind071
  vars:
    node_exporter_archive: https://github.com/prometheus/node_exporter/releases/download/v1.1.0/node_exporter-1.1.0.linux-amd64.tar.gz
    node_exporter_bin: /home/fin33rus/node_exporter-1.1.0.linux-amd64/node_exporter
    prometheus_archive: https://github.com/prometheus/prometheus/releases/download/v2.24.1/prometheus-2.24.1.linux-amd64.tar.gz
    prometheus_bin: /home/fin33rus/prometheus-2.24.1.linux-amd64/prometheus
    prometheus_consoles: /home/fin33rus/prometheus-2.24.1.linux-amd64/consoles
    prometheus_conslole_library: /home/fin33rus/prometheus-2.24.1.linux-amd64/console_libraries
    grafana_deb: https://dl.grafana.com/oss/release/grafana_7.4.0_amd64.deb
    home_dir: /home/fin33rus/My_lab/repo1/Linux/Ansible/Prometeus/
  tasks:
  - name: add prometheus users
    user:
      name: prometheus
      shell: /usr/sbin/nologin
      create_home: no 
  - name: add node_exporter user
    user:    
      name: node_exporter
      shell: /bin/false
      create_home: no 
  - name: Creates directory
    file:
      path: /etc/prometheus
      state: directory
      owner: prometheus
      group: prometheus
  - name: creates prometheus directory
    file:    
      path: /var/lib/prometheus
      state: directory
      owner: prometheus
      group: prometheus
  - name: Unarchive node_exporter
    unarchive:
      src: '{{ node_exporter_archive }}'
      dest: /home/fin33rus
      remote_src: yes
  - name: copy node_exporter.bin
    copy:
      src: '{{ node_exporter_bin }}'
      dest: /usr/local/bin
      mode: 0755
      remote_src: yes
  - name: add node_exporter service
    copy:
      src: '{{ home_dir }}node_exporter.service'
      dest: /etc/systemd/system/node_exporter.service
  - name: just force systemd to reread configs 
    systemd:
      daemon_reload: yes
  - name: enable service node_exporter
    systemd:
      name: node_exporter
      state: started
      enabled: yes
  - name: Unarchive prometheus
    unarchive:
      src: '{{ prometheus_archive }}'
      dest: /home/fin33rus
      remote_src: yes
  - name: copy prometeus.bin
    copy:
      src: '{{ prometheus_bin }}'
      dest: /usr/local/bin
      owner: prometheus
      group: prometheus
      mode: 0755
      remote_src: yes
  - name: copy consoles files
    copy:
      src: '{{ prometheus_consoles }}'
      dest: /etc/prometheus
      owner: prometheus
      group: prometheus
      remote_src: yes
  - name: copy consoles libraries
    copy:
      src: '{{ prometheus_conslole_library }}'
      dest: /etc/prometheus
      owner: prometheus
      group: prometheus
      remote_src: yes
  - name: add prometheus.yml
    copy:
      src: '{{ home_dir }}prometheus.yml'
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
  # - name: add alert.rules.yaml
    # copy:
    #   src: '{{ home_dir }}alert.rules.yaml'
    #   dest: /etc/prometheus/alert.rules.yaml
    #   owner: prometheus
    #   group: prometheus
  - name: add prometheus service
    copy:
      src: '{{ home_dir }}prometheus.service'
      dest: /etc/systemd/system/prometheus.service
  - name: just force systemd to reread configs
    systemd:
      daemon_reload: yes
  - name: enable service prometheus
    systemd:
      name: prometheus
      state: started
      enabled: yes
  - name: adduser for grafana
    command: apt-get install -y adduser libfontconfig1
  - name: Install grafana
    apt:
      deb: '{{ grafana_deb }}'
  - name: just force systemd to reread configs
    systemd:
      daemon_reload: yes
  - name: enable service grafana-server
    systemd:
      name: grafana-server
      state: started
      enabled: yes      
  - name: reload prometheus
    systemd:
      name: prometheus
      state: restarted
  - name: reload grafana
    systemd:
      name: grafana-server
      state: restarted