- name: installing and configuring elasticsearch cluster
  hosts: elknodes
  vars:
    elk_deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-amd64.deb
  tasks:  
  - name: install requirement packages
    apt:
      name: apt-transport-https
  - name: Install a .deb package from the internet
    apt:
      deb: '{{ elk_deb }}'
  - name: start elasticsearch
    ansible.builtin.service:
      name: elasticsearch
      state: started
  - name: Enable service elasticsearch
    ansible.builtin.service:
      name: elasticsearch
      enabled: yes
      