- name: installing and configuring bind9 on ubuntu
  hosts: ub-bind071
  vars:
    bind_home_dir: /home/fin33rus/My_lab/repo1/Linux/Ansible/Bind/
  tasks: 
  - name: Install the package 'bind9'
    apt:
      name: bind9
  - name: add options
    copy:
      src: '{{ bind_home_dir }}/named.conf.options'
      dest: /etc/bind/named.conf.options
  - name: add local conf
    copy:
      src: '{{ bind_home_dir }}named.conf.local'
      dest: /etc/bind/named.conf.local
  - name: add zone file
    copy:
      src: '{{ bind_home_dir }}site1.int'
      dest: /var/cache/bind/site1.int
  - name: add default zones config
    copy:
      src: '{{ bind_home_dir }}named.conf.default-zones'
      dest: /etc/bind/named.conf.default-zones
  - name: add lan zone
    copy:
      src: '{{ bind_home_dir }}db.192.168.1'
      dest: /etc/bind/db.192.168.1
  - name: enable service bind9
    systemd:
      name: bind9
      state: started
      enabled: yes
  - name: reload bind
    systemd:
      name: bind9
      state: restarted