- name: setup elasticsearch cluster
  hosts: ub-elk077
  vars:
    node_home_dir: /home/fin33rus/My_lab/repo1/Linux/Ansible/Elasticsearch/cluster/node3/
  tasks: 
  - name: add elasticsearch configuration
    copy:
      src: '{{ node_home_dir }}elasticsearch.yml'
      dest: /etc/elasticsearch/elasticsearch.yml
  - name: reload elasticsearch
    ansible.builtin.service:
      name: elasticsearch
      state: restarted