---
- name: create group_one
  hosts: elk72
  become: true
  vars:
    mygroup: "group_one"
  tasks:
    - name: create group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: present
