---
- name: create user account
  hosts: elk72
  become: true
  tasks:
    - name: create user_one
      ansible.builtin.user:
        name: user_one
        password: "{{ 'password' | password_hash('sha512', 'mypassword') }}"
        shell: "/bin/bash"
        system: false


