---
- name: create user account
  hosts: elk72
  become: true
  vars:
    mypass: "12345678"
  tasks:
    - name: create user_one
      ansible.builtin.user:
        name: user_one
        password: "{{ mypass | password_hash('sha512') }}"
        shell: "/bin/bash"
        system: false


