# Generated by Django 2.2.4 on 2019-10-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wahashop',
            options={'verbose_name': 'Ваха магазин', 'verbose_name_plural': 'Ваха магазины'},
        ),
        migrations.CreateModel(
            name='WahaGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название игры')),
                ('short_description', models.CharField(max_length=30, verbose_name='Краткое описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('wahashop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.WahaShop')),
            ],
            options={
                'verbose_name': 'Ваха игра',
                'verbose_name_plural': 'Ваха игры',
            },
        ),
    ]
