# Generated by Django 2.2.4 on 2019-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_auto_20191003_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wahagame',
            options={'ordering': ['name'], 'verbose_name': 'Ваха игра', 'verbose_name_plural': 'Ваха игры'},
        ),
        migrations.AddField(
            model_name='wahagame',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='application1/photos', verbose_name='Фото'),
        ),
    ]
