---
- name: change configuration from file
  hosts: router1
  gather_facts: false
  connection: network_cli
  tasks:
    - name: change interface description
      ios_config:
        src: router1/config.txt
        save_when: modified