---
- name: show config
  hosts: router1
  gather_facts: false
  tasks:
    - name: show config
      ios_command:
        commands:
          - sh run
      register: output
    - debug:
        var: output.stdout
    - name: save output to a file
      copy:
        content: "{{ output.stdout | replace('\\n', '\n') }}"
        dest: "/home/ivanf/{{ inventory_hostname }}.txt"